name: ease
description: Etiqa Sales Evolution

version: 2.0.22120200+1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # aes256gcm: ^1.0.1
  bloc: ^8.1.0

  camera: ^0.10.0+4 # Access camera to capture image
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  crypto: ^3.0.2
  cryptography: ^2.0.5
  cryptography_flutter: ^2.0.2
  cupertino_icons: ^1.0.5 # Use with the CupertinoIcons class for iOS style icons.
  currency_text_input_formatter: ^2.1.8

  device_info_plus: ^8.0.0
  dio: ^4.0.6 # HTTP Client

  encrypt: ^5.0.1 # encrypt & decrypt web api
  # enum_to_string: ^2.0.1
  equatable: ^2.0.5 # Pair with Flutter bloc for singleton

  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.3 # Need additional setup if deploy for Android
  firebase_performance: ^0.9.0+6
  firebase_remote_config: ^3.0.6

  flutter_bloc: ^8.1.1 # State Management
  flutter_html: ^3.0.0-alpha.6 # HTML string to Text view
  flutter_html_all: ^3.0.0-alpha.6
  flutter_local_notifications: ^13.0.0 # Local push notification
  # flutter_multi_formatter: ^2.9.5
  flutter_mailer: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_secure_storage: ^6.1.0
  flutter_staggered_grid_view: ^0.6.2 # For dynamic gridview height based on content
  # formz: ^0.4.0                      # New Business Quotation Form

  gallery_saver: ^2.3.2

  html_character_entities: ^1.0.0+1 # Convert Medical Exam HTML data
  http: ^0.13.5

  image_picker: ^0.8.6 # Image picker for profile photo
  image: ^3.2.2
  intl: ^0.17.0 # For date time
  # introduction_screen: ^2.1.0        # For Walkthrough pages

  jiffy: ^5.0.0

  linked_scroll_controller: ^0.2.0 # New Business, SI Table sync scroll
  lint: ^2.0.1
  local_auth: ^2.1.2

  native_device_orientation: ^1.1.4 # For camera to detect current orientation

  package_info_plus: ^3.0.2
  password_strength: ^0.2.0 # Estimate password strength
  path: ^1.8.2
  path_provider: ^2.0.11 # To setup local db
  pdf_viewer_plugin: ^2.0.1
  # provider: ^6.0.0

  safe_device: ^1.1.2
  scrollable_positioned_list: ^0.3.5
  # secure_application: ^3.5.3
  sembast: ^3.3.1 # Local db
  share_extend: ^2.0.0 # Medical Exam, to share medical doc
  shared_preferences: ^2.0.15 # Medical Exam, to save medical appointment id
  signature: ^5.3.0 # Getting signature and export to image
  sortedmap: ^0.5.2

  timezone: ^0.9.1

  url_launcher: ^6.1.7 # Medical Exam, Launch map url
  uuid: ^3.0.7

  webview_flutter: ^3.0.4

  # test
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

  com_etiqa_flutter_crypto:
    path: plugins/etiqacrypto/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon/app_icon@2x.png"

flutter:
  uses-material-design: true
  assets:
    - i18n/en.json
    - i18n/ms.json
    - assets/images/
    - assets/images/health_questions/
    - assets/images/dashboard/
    - assets/files/
  fonts:
    - family: Meta
      fonts:
        - asset: assets/fonts/metapro-Bold.otf
          weight: 900
        - asset: assets/fonts/metapro-Bold.otf
          weight: 800
        - asset: assets/fonts/metapro-Medium.otf
          weight: 600
        - asset: assets/fonts/metapro-Normal.otf
          weight: 400
        - asset: assets/fonts/metapro-Thin.otf
          weight: 300
